FROM python:3.10-slim
# Set the working directory in the container
WORKDIR /app    

RUN apt-get update && apt-get install -y gcc

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
CMD ["python", "app/log_stream_predictor.py"]